fragment SiteParts on Site {
  __typename
  eyebrow
  title
  description
  stackLabel
  stackValue
  hostLabel
  hostValue
  modeLabel
  modeValue
}

fragment PostParts on Post {
  __typename
  title
  date
  summary
  tags
  draft
  images
  layout
  body
}

fragment AuthorParts on Author {
  __typename
  name
  avatar
  occupation
  company
  email
  github
  body
}
